---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  url: https://github.com/istio/istio
  ref:
    # renovate: repoHandle=istio/istio
    tag: 1.9.5
