---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  values:
    gateways:
      istio-ingressgateway:
        loadBalancerIP: "34.91.159.136"
    meshConfig:
      extensionProviders:
        - name: "oauth2-proxy"
          envoyExtAuthzHttp:
            service: "oauth2-proxy.oauth2-proxy.svc.cluster.local"
            port: "4180"
            includeHeadersInCheck: ["authorization", "cookie"]
            headersToUpstreamOnAllow: ["authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token"]
            headersToDownstreamOnDeny: ["content-type", "set-cookie"]
