---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
spec:
  releaseName: argo-workflows
  chart:
    spec:
      # renovate: registryUrl=https://argoproj.github.io/argo-helm
      chart: argo
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  interval: 5m
  timeout: 30m
  values:
    singleNamespace: true
    installCRD: true

    workflow:
      serviceAccount:
        create: false
        name: argo-workflow
      rbac:
        create: true

    controller:
      serviceAccount: argo
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-pool-profile
                    operator: In
                    values:
                      - system
      metricsConfig:
        enabled: true
      telemetryConfig:
        enabled: true
      serviceMonitor:
        enabled: true

    server:
      enabled: true
      createServiceAccount: true
      serviceAccount: argo-server
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-pool-profile
                    operator: In
                    values:
                      - system
