apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
spec:
  chart:
    spec:
      # renovate: registryUrl=https://argoproj.github.io/argo-helm
      chart: argo
      version: 0.16.8
  values:
    controller:
      replicas: 2
      pdb:
        enabled: true
        minAvailable: 1
        maxUnavailable: 1
    server:
      enabled: true
      replicas: 2
      pdb:
        enabled: true
        minAvailable: 1
        maxUnavailable: 1
    useDefaultArtifactRepo: true
    useStaticCredentials: true
    artifactRepository:
      gcs:
        bucket: st-nowca-staging-artifacts
        keyFormat: '{{workflow.namespace}}/{{workflow.name}}/'
        serviceAccountKeySecret:
          name: gcs-credentials
          key: cloud
