apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cert-manager-cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBIliu3wX9r86NQ9JLf1lRcdfZIY8Eru3JnfIdNMg0aqcCqZYHvUSkFzA74Rr8TPXuARQ8BmkB9dIJG5W3ORPEH6Wd9vnbnT+PaS/ZBo42oWAOZZdw8NBMXplA+x6N7JJTkrW2pMTYq8Zo+UkCU7BjQuCojtvG9mjLfaokYYavNe4zkBHwnF3gSXwwJUznu53r1/R06aEb8cpbHjsVw+RRm2Q6gV2veuxh55EVIIlrTHIjwbDL5QS3iI381/n7VFSHwUYj9ZV4w8CJuwf2MjVD3l4V5ahRHyXbxN4G/bBZ5Q5O0JYWMqzJFGkhzcHHAx71wcmj/aIfxvNEuiQgrI6+bKokT3u8PCXYnicZ02QpBOjdgrKML1yn57zChMHlxPphv9rZP/OE8MNuMQfws38FrQm7F6gJ6q0bisc1m8guwqEA6fRd3JUmFuZibWNKOnW5GiwFoEDePTDlrWF28J2DsZIsUo7GYZWDhWY5pZp4t8Wjs+dU/HFSMnDLTysuLcLc7FJRUqgKAkX7z92GQq4kPCSSIRpxOT19wL0/HBkI5G9SIeE4wCqmRdSyU8t/x2uv/ktmADTkdsiqtU0/R6DsFtbKH0RqrMWS/l7cD0FZD9taC4cQdOYiiW6xxAFKcfRtf4n/Ankzs4H68r1LZB6/3vM/VNHNrBOXjGizGSudUQIIDRy2TuEvUeV1DNzS8EFMWIg9cWt9ziMn4iqnkoIKU31gkhitvxpRmOsPz3mVmD9osfRMgaoQH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cert-manager-cloudflare-credentials
      namespace: cert-manager

