apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io
      chart: cert-manager
      version: 1.2.0
  values:
    replicaCount: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
