apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: istio-system
spec:
  releaseName: oauth2-proxy
  dependsOn:
    - name: istio
    - name: istiod
    - name: istio-ingress
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  timeout: 30m
