---
version: '3'

includes:
  cluster:
    taskfile: .taskfiles/Taskfile_cluster.yml
    dir: ./infrastructure/cluster
  backup:
    taskfile: .taskfiles/Taskfile_tf_generic.yml
    dir: ./infrastructure/backup
  buckets:
    taskfile: .taskfiles/Taskfile_tf_generic.yml
    dir: ./infrastructure/buckets
  disks:
    taskfile: .taskfiles/Taskfile_tf_generic.yml
    dir: ./infrastructure/disks
  secrets:
    taskfile: .taskfiles/Taskfile_secrets.yml
    dir: .
