---
version: '3'

env:
  TF_WORKSPACE: staging
  TF_CLI_ARGS_plan: -input=false

includes:
  clusters:
    taskfile: .taskfiles/Taskfile_cluster.yml
    dir: ./infrastructure/clusters
  backups:
    taskfile: .taskfiles/Taskfile_tf_generic.yml
    dir: ./infrastructure/backups
  buckets:
    taskfile: .taskfiles/Taskfile_tf_generic.yml
    dir: ./infrastructure/buckets
  disks:
    taskfile: .taskfiles/Taskfile_tf_generic.yml
    dir: ./infrastructure/disks
  registry:
    taskfile: .taskfiles/Taskfile_tf_generic.yml
    dir: ./infrastructure/registry
  endpoints:
    taskfile: .taskfiles/Taskfile_tf_generic.yml
    dir: ./infrastructure/endpoints
  artifacts:
    taskfile: .taskfiles/Taskfile_tf_generic.yml
    dir: ./infrastructure/artifacts
  databases:
    taskfile: .taskfiles/Taskfile_tf_generic.yml
    dir: ./infrastructure/databases
  secrets:
    taskfile: .taskfiles/Taskfile_secrets.yml
    dir: .

tasks:
  buildup:
    desc: "Bring up infra"
    cmds:
      # - task: disks:apply
      - task: clusters:apply
  teardown:
    desc: "Tear down infra"
    cmds:
      - task: clusters:destroy
      # - task: disks:destroy
