apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ca
  namespace: flux-system
spec:
  interval: 5m
  suspend: false
  dependsOn:
  - name: crds
  - name: sources
  - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/ca/staging
  prune: true
  validation: client
  healthChecks:
  - apiVersion: v1
    kind: Secret
    name: cloudflare-cluster-issuer-credentials
    namespace: cert-manager
  - apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    name: cloudflare
