---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  interval: 5m
  suspend: false
  dependsOn:
    - name: flux-alerts
    - name: crds
    - name: istio
    - name: sources
    - name: secrets
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/certificates/staging
  prune: true
  validation: client
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: cloudflare-token
      namespace: cert-manager
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt
