apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: certs
  namespace: flux-system
spec:
  interval: 5m
  suspend: false
  dependsOn:
  - name: secrets
  - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/certs/staging
  prune: true
  validation: client
  healthChecks:
  - apiVersion: v1
    kind: Secret
    name: cert-manager-cloudflare-credentials
    namespace: cert-manager
  - apiVersion: cert-manager.io/v1
    kind: Issuer
    name: cloudflare
    namespace: cert-manager
