---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gotk-alerts
  namespace: flux-system
spec:
  interval: 5m
  suspend: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deployments/staging/gotk-alerts
  prune: true
  validation: client
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: slack-webhook
      namespace: flux-system
