---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  suspend: false
  dependsOn:
    - name: flux-alerts
    - name: crds
    - name: sources
    - name: secrets
    - name: monitoring
    - name: istio
    - name: gateways
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/grafana/staging
  prune: true
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: grafana
      namespace: grafana
