apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 5m
  suspend: false
  dependsOn:
  - name: crds
  - name: secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/istio/staging
  prune: true
  validation: client
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: istio
    namespace: istio-system
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: istiod
    namespace: istio-system
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: istio-ingress
    namespace: istio-system
