apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 5m
  suspend: false
  dependsOn:
  - name: secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/istio/staging
  prune: true
  validation: client
