---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: jaeger
  namespace: flux-system
spec:
  interval: 5m
  suspend: false
  dependsOn:
    - name: flux-alerts
    - name: crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/jaeger/staging
  prune: true
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: jaeger
      namespace: tracing-system
