---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nfs
  namespace: flux-system
spec:
  interval: 5m
  suspend: true
  dependsOn:
    - name: flux-alerts
    - name: crds
    - name: istio
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/nfs/staging
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: nfs-server
      namespace: nfs
