apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: scheduling
  namespace: flux-system
spec:
  interval: 5m
  suspend: true
  dependsOn:
  - name: sources
  - name: crds
  - name: secrets
  - name: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/scheduling/staging
  prune: true
  validation: client
