apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
  - name: sources
  - name: crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/secrets/staging
  prune: true
  validation: client
  healthChecks:
  - apiVersion: v1
    kind: Secret
    name: sealed-secrets-key
    namespace: kube-system
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: sealed-secrets
    namespace: kube-system
