apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: sources
    - name: crds
    - name: secrets
    - name: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/traefik/staging
  prune: true
  validation: client
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: cloudflare-credentials
      namespace: traefik
