apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 5m
  suspend: false
  dependsOn:
  - name: sources
  - name: crds
  - name: secrets
  - name: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/velero/staging
  prune: true
  validation: client
  healthChecks:
  - apiVersion: v1
    kind: Secret
    name: velero-gcs-credentials
    namespace: velero
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: velero
    namespace: velero
