apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secret-cloudflare-credentials.yaml
  - config-map.yaml
  - ../../base/traefik
patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: traefik
    spec:
      chart:
        spec:
          version: "9.14.2"
      values:
        additionalArguments:
          - --providers.file.filename=/data/traefik-config.yaml
          - --entrypoints.websecure.http.tls.certresolver=letsencrypt
          - --entrypoints.websecure.http.tls.domains[0].main=staging.nowca.st
          - --entrypoints.websecure.http.tls.domains[0].sans=api.staging.nowca.st,docs.staging.nowca.st
          - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
          - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
          - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
          - --certificatesresolvers.letsencrypt.acme.email=webmaster@nowca.st
          - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53
          - --certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json
          - --api.insecure=true
          - --accesslog=true
          - --log.level=INFO
        ports:
          web:
            redirectTo: websecure
        env:
          - name: CF_DNS_API_TOKEN
            valueFrom:
              secretKeyRef:
                key: apiToken
                name: cloudflare-credentials
        ingressRoute:
          dashboard:
            enabled: false
        deployment:
          enabled: true
          kind: Deployment
          replicas: 2
        persistence:
          enabled: true
          path: /certs
          size: 128Mi
        volumes:
          - mountPath: /data
            name: traefik-config
            type: configMap

