apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secret-cloudflare-credentials.yaml
  - ../../base/traefik
patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: traefik
    spec:
      chart:
        spec:
          version: "9.14.2"
