apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: traefik
spec:
  encryptedData:
    apiToken: AgBP8rFJtyskyVfzCk1jd0FWhjJ0ekTiSfGEbldseOP4K7bVthGwJ6um6ty/pyKgtNsuJPtWFbk2S+L/RkJLIA892VFYYNp7po68bwerUL1b7/SOHx4pMUzEZ0iTF+Z6h7qZFi7UzWD1vWSWQLNG1BR5ZtjwtXPUXAiAGPFIjv9glNqQkRjp17q5xdEqkaDg12JN8q6m4I/10djZivYD2l9gn7HpygWnOTyjjNFL3RzQXv5lWVepghT2V8nbwZshw6LcHR2HqOP0VHqEqcT/aiq2Z8LmmzW/fQtRBW6odYExxcWHygYeSGc5cbMsJMeU/zT5LpXH8uw5mMSD15oRRnmP+i7F7DOvFfE+waJiH/cX29yv5/GPikxsWSQA6XUtZuh+crKelKWheAGkSj3aRAryVm+q6LrCSOiUpfp2TPMiAfGdPHEp3p2Hdsc3ye7AmRvHafSsb1T81t+fs5PAJgr8QfmvFgH5W40swQdz/paTtsof9crgTD7DjJ1hT3uvB+rvjcrhV/DDT4LhwfB/XnktVKWKfARF7Yf8ACYodGoJXmwk0pp0cnS3sEn/ygAFIsO4RkIMBgTKmIm/7z2InaYeZxwWncN/ZnqOE/XoYXJziW0L6HqaQKY6/DbvQz3+euI629LVmhn+1VqzQ300PSpw5QEbWafl1ppzyBJOKq4s1QJUqRMQmDQd+s2UY8xQdbQkKyss++tBSBAuiGuaaBPzlWbRb7E4I+ETOKw4b/d2TlC0zPFnyhHu
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: traefik
    type: Opaque

