---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-login
  namespace: grafana
spec:
  encryptedData:
    values.yaml: AgBu4XIozbiVKvT/f5NKPvaom4V3MXu2FnIDHy1MdHkSXTy61FArlJ/FgAswRd1nSt/AeXPM8JwQZ09JjF/9O3UOjALvTCeemFHi5hos2Nuki4LxHFd7MTzy6ZwdQYNCh8o0bTMdOarrcLxE1GLrkdErCR9i/3K/DJlBJU1IEwjlYQU+qexCukvvIywbnn48t9NRn7E9fE8F913prdkWpXamcgE4wxtxAFlYeICLvadLP4vABoSawz6yd6KzBnfSSDgQxgXlU5oDN7Gzjrop74SeeG59BTYUj0/hUwg1lFHmjEKjZT23d4tkjhQGZyzcQ8g4zvQIpJGmIHIvq2Sal+J1sh4K5ed74HHIaubYUEynOsXJyVtJHRNNrXguOSo6IZPhGVx6jG+R4IapmvQVTP3jaCx/jOWo9OMuJUclIeEnT9K4MMY0w1voUQ3NRXBCoysNDZI+r1oqIBrC/6HsStC9l4OPgIIQsg8K8xIMc5/ih/+iw1YZLueKKH7AhhYEQAQd5TIpDH0D4k+fdjhqaZyNBN34rIfofn1ut48OqjmII8zPMXmKJnxR2Qsq/vKgX8ojLqT6/kYCmYlf1Azd8Hmuq2PRC2Z6naxNu9J5kXIe0705Na5HuPIRdzgq+Fq++hMDhnBp4XOJA0+37dgI8eToIUoQmQ/NAwWU0qmn2Iowjp41iB2MeFt8KlkiE7fLDpBWH+FOMP6C5W5AenH9af/UbNnFwIYK9/9JzWAATzPBr9EJb6Yd7kgEXTg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-login
      namespace: grafana
    type: Opaque
