---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-events
spec:
  chart:
    spec:
      # renovate: registryUrl=https://argoproj.github.io/argo-helm
      chart: argo-events
      version: 1.6.2
