---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
spec:
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/descheduler/
      chart: descheduler
      version: 0.20.0
