apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sealed-secret-gcs-credentials.yaml
- ../../base/argo
patchesStrategicMerge:
- |-
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: argo
  spec:
    chart:
      spec:
        version: "0.16.6"
    values:
      controller:
        replicas: 2
        pdb:
          enabled: true
          minAvailable: 1
          maxUnavailable: 1
      server:
        enabled: true
        replicas: 2
        pdb:
          enabled: true
          minAvailable: 1
          maxUnavailable: 1
      artifactRepository:
        gcs:
          bucket: st-nowca-staging-artifacts
          keyFormat: "{{workflow.namespace}}/{{workflow.name}}/"
          serviceAccountKeySecret:
            name: gcs-credentials
            key: cloud
