apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/grafana
- sealed-secret-grafana-credentials.yaml
patchesStrategicMerge:
- |-
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: grafana
  spec:
    chart:
      spec:
        version: "6.4.2"
    values:
      podAnnotations:
        configmap.reloader.stakater.com/reload: "grafana-credentials"
    valuesFrom:
    - kind: Secret
      name: grafana-credentials


