apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-credentials
  namespace: monitor-system
spec:
  encryptedData:
    values.yaml: AgBG3d3S/4AKRO3zGu77eX3h8/Q+xkEhnTf84ueA/5MVFKdZKhYl0OPckzARyHaemdmh7ZFB3UML3OFqp0meTUezIL0MPa5Lhs0nT8yOv33jytNcT/rR0j4OPypUMjo8ptoAAi5e7AUuj512i+u3qUS7ZUfxI4vgvhxwJEtGX0EIjrUvmJlNm1NvoInuhjxXUpsQ77crcTh3bgX9YG/TSi0CEtqlET0vpqoipWYuU+Xe/Vf8CmGdlXLqeTmrDs9SzZlFUJwAykonkBHd3FxXxFJiZTfclrmyAesVtNYR+8BKHivPv52yAOy/oEHQYZJdQoy9YPlvZRuidCmD/m1hP35/bVOnvSNk+w0FUXewG64J0qZ0VjVS5/+Vp/Ab1VoweaZguUvFFFmksRJHdy0Tca8gZ43zOtkbuANtvyOTS3YTeGyJDZyz6IsDuV0lbYBsgOWLzBapQOPkOpG5foZUK0hK3ndE1/M5v9tJ8c7bzEwkN0IsLty8pHHe8gjlVHk1qaP69jAqWPmbBFn+x/3XxfofOiOT3aWPALbnkJFxaWm2MFz1opu80dk44GHAaZVJ9lV9yL7TEcWyQJcvlvXVlKGHyufkM1MqQ0mjI0ez9+SsXNdh2Qzl759MRay05+ehrSGDy9IyG/CZSF/t9Z3O/hA9gujBKVfQX9hachDqLDE3okJbcohaavyvBXJqha2Zoow5xub0TQun6QBLfoKchC1aG50RF+c40no8nakZw5dI/gy75rIScwcW0xg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-credentials
      namespace: monitor-system
    type: Opaque

