apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
spec:
  chart:
    spec:
      # renovate: registryUrl=https://stakater.github.io/stakater-charts
      chart: reloader
      version: v0.0.87
