---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: sebastian@markow.io
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-account-credentials
    solvers:
      - dns01:
          cloudflare:
            email: sebastian@markow.io
            apiTokenSecretRef:
              name: cloudflare-token
              key: api-token
