apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo.yaml
  - bitnami.yaml
  - descheduler.yaml
  - grafana.yaml
  - prometheus-community.yaml
  - sealed-secrets.yaml
  - stakater.yaml
