apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: healthcheck-webhook-url
  namespace: monitor-system
spec:
  encryptedData:
    address: AgB7mZmMOw7UvB2PEpsoZhwGI20OdgCC8t67+idfb4xrsjUxN7Nu0AJ/IWu8wKYqzI8bJVb86u8JhhzT3tVo/7EDnplOJtmdpWdIL88CXIf5ODzqdvBEJVRVP7dFPup1QpkYG8of7TJOGmsYutoWVZvRjbinRpiqB6lpYQyMJF44z6VjGhaoWRicDKnF27naSO1z7RR22j951oqF9dbBYY5Xqz7zGF1gDuBMy707enVyunClNeCG0fuKYdbIlE44tXw5YdmE/A6wQzUU/FJYiR8YOlletrnCMtoTgff5o92ds385TXX7l59RhyeTs8l//WRBphfya7OqOf/zIxyuUUwP0+4ZZwAfzzQvXm7JMEkYgDbZuvOLD2NAsXlzdlHEWlwWZyajvkai0fYMPQUm4fR7fvcDx1603XLTu94AE1vAbSeI5ZnD958nCM29Wm2i6haqad/5H/HqjcBArt0bW/j6PkVlwccUn+Wz2FArxnW8FsWkvszy19iChyTRlbjA3zQ4EGsC5mQ6O80bvZHlDVmBiAA6i76bNQIC8fDYs/A+4VZ9EIOjQTjYigA40hHq3AoYUrcJMmCSw3tidi78MmyiP8beKqxwDq4D4fMlDhePDcy8SjitLgReUPcAO1KtzcewXj7UradUaZGm3piqgm/MUTvdbpbHLGdpKd2X2/k4Y4eOXTTHg26q7rFsQwqzvQUJ/Hu2FJ49gscVSF3kL6UxuI2Xs/934RNFhZyzu2u2GaegakNsGLYPGqcTd9ktgJtQlH2Qg6TRUw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: healthcheck-webhook-url
      namespace: monitor-system

