apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/velero
patchesStrategicMerge:
  - sealed-secret.yaml
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: velero
    spec:
      chart:
        spec:
          version: "2.14.8"
      values:
        initContainers:
          - name: velero-plugin-for-gcp
            image: velero/velero-plugin-for-gcp:v1.1.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        credentials:
          useSecret: true
          existingSecret: velero-key
        configuration:
          provider: velero.io/gcp
          backupStorageLocation:
            name: default
            bucket: velero-staging-backup
          volumeSnapshotLocation:
            name: default
            config:
              snapshotLocation: europe-west4
