apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sealed-secret-gcs-credentials.yaml
- ../../base/velero
patchesStrategicMerge:
- |-
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: velero
  spec:
    chart:
      spec:
        version: "2.14.12"
    values:
      rbac:
        create: true
      initContainers:
        - name: velero-plugin-for-gcp
          image: velero/velero-plugin-for-gcp:v1.1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins
      credentials:
        useSecret: true
        existingSecret: gcs-credentials
      configuration:
        provider: gcp
        backupStorageLocation:
          name: default
          bucket: st-nowca-staging-backup
        volumeSnapshotLocation:
          name: default
          config:
            snapshotLocation: europe-west4
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      installCRDs: true
      enableHelmHooks: true
