apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/velero
patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: velero
    spec:
      chart:
        spec:
          version: "2.14.7"
      values:
        credentials:
          existingSecret: velero-gcp-key
        configuration:
          provider: velero.io/gcp
          backupStorageLocation:
            name: default
            bucket: velero-staging-backup
          volumeSnapshotLocation:
            name: default
            config:
              snapshotLocation: europe-west4
  - sealed-secret.yaml
