apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: istio-system
spec:
  releaseName: oauth2-proxy
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  timeout: 30m
  values:
    extraArgs:
      provider: github
      github-org: nowcast-ml
      whitelist-domain: .nowca.st
      cookie-domain: .nowca.st
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-redis
  namespace: istio-system
spec:
  releaseName: oauth2-redis
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  timeout: 30m
  values:
