---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-general
  namespace: flux-system
spec:
  suspend: false
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-helmrepositories
  namespace: flux-system
spec:
  suspend: false
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: HelmRepository
      name: '*'
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-helmreleases
  namespace: flux-system
spec:
  suspend: false
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      namespace: 'kube-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'monitor-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'istio-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'argo'
      name: '*'
    - kind: HelmRelease
      namespace: 'velero'
      name: '*'
