---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-events
spec:
  releaseName: argo-events
  chart:
    spec:
      # renovate: registryUrl=https://argoproj.github.io/argo-helm
      chart: argo-events
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  interval: 5m
  timeout: 30m
  values:
    namespace: argo
    singleNamespace: true
    serviceAccount: argo-events
    sensorController:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-pool-profile
                    operator: In
                    values:
                      - system
    eventsourceController:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-pool-profile
                    operator: In
                    values:
                      - system
    eventbusController:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-pool-profile
                    operator: In
                    values:
                      - system
