---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA1KGYVHQU6FDGlEFRZS3CMCRvubj9kU4CMjcmsI3ZGyhQdc0O4vWBli4G1ASWHZk+ZZEfO+dV2Ig+S3WQ5FXOWLRtPd9ES6K26HfMUQjM64RZruFQ9cMJRw3msI/NBsqS/eKwc74yFQ6hytTtKiy6BLQ+pA8UEgUDe7m29fdn3GtcBRC11M9PqL0OMdMISpXqQlDoH41YgwAX3pvAW15LzK8fq9RqUbHfibCguq3AvJbsSF+B9uGIxWjiOA5quNzpr+I2KoVjo2bIBjUrkSE11HwhTNLOjhn9M69kGXHbfiEhP//ZleRIVwB6YHxe8ScA3iieJtDM2ZrgFIdUt79V9ItKJFiHO9Whqa+JrI9kVYUgmq7XQiUhBTkI3P9Vii0VzMK2E60Y6POIUyBx6LnmmyyysC2RQNnw8fbJ9dMHXavoF+1dPCwX2kpPjw30o8LPcvgpm3AzjoEyhAi4ch6PAj3pEPfttrd6M/EWu6l4fD7aRVal+3HLWVeduXZk2tPTMa+vA8sehYWLSc/yR65+omW0mmrYMK21uUeeP2QBQnGw12/vJ6/fJdu4BWyqBuHH4ZOowFFdmCpqg4fZNP8P8DZJYFfjRNlVH+ttirYlL9BqPmjl5GdqoPO+uzqZjiu8YfM3tUow/szkxL83xVn8mriuSD9BSJixWnuD00mik3nc1mpUFKEqtBYXOeKiwusxuDOM2l7jzcsJW2jaEvbkWkntUm8vZX5sUXZupbL4SmPel9W8PI9g9
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-token
      namespace: cert-manager
