apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio
spec:
  releaseName: istio
  chart:
    spec:
      chart: ./manifests/charts/base
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: flux-system
  interval: 5m
  timeout: 30m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
spec:
  releaseName: istiod
  dependsOn:
    - name: istio
  chart:
    spec:
      chart: ./manifests/charts/istio-control/istio-discovery
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: flux-system
  interval: 5m
  timeout: 30m
