apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    email: sebastian@markow.io
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-account-credentials
    solvers:
    - dns01:
        cloudflare:
          email: sebastian@markow.io
          apiTokenSecretRef:
              name: cloudflare-cluster-issuer-credentials
              key: api-token
