---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      # renovate: registryUrl=https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  interval: 5m
  timeout: 15m
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-pool-profile
                  operator: In
                  values:
                    - system
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    controller:
      create: true
    serviceAccount:
      create: true
    rbac:
      create: true
    ingress:
      enabled: false
    crd:
      create: true
      keep: true
    serviceMonitor:
      create: true
