---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  chart:
    spec:
      # renovate: registryUrl=https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      version: 1.16.1
