---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: tracing-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://jaegertracing.github.io/helm-charts
      chart: jaeger-operator
      version: 2.23.0
