apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: slack-webhook-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCc0Dnsf6F630r7qFJtqLwoizlYKn86O+HANLLYXWTSlRazaJComa1i+ubNqbJNO6Emwuc0+Ak0SVMjjVqWkwNoyatNxhariFi5xk6obLVPilvYaDWRmTFUnySOxfcJ3dUd3HwKQudfpL9RDiEesG3kHuGU9Ww2RVk0HO4D2rEBf6rAU+4FzeTqs5eG4oZMl9o/I0wFxvoJoCEm0EEM+fzqoSJVhEjcnV6mIbqaCgOFWm4F+J79wjyqmpWZmEB7uSURwBaM+ob5ojsop7LOJeSMMbmLbgZRiNojVzKQ7wCnQ5IIoHH5ZWL2jhZNPpJK6yTN3hZaSlXUgDuGJ25Lg4hQ0d1mmnFLDtC7FZQL8dVCAmFSoPdYKr/qva82gAbutoWCKuqjpo8FeK0vxFOAIwxFbLPW5aL3BcyKm3Gji0bZuPT3uOMA7HI7bhnB/MVVToqZemmExveL6XCwM5KealFcaWpy+URtaiSMO6kWdCXieSG0G1B1u7dJDmyhbEqfolBncvzvrCPNtByAd/VG+m9Hima+0JygYD6DCPfHCaOFytho/q8dyWgmG7EXUH6q6TcD23dt9DgzyLYg5yl0syeMk6c/S86QVphei+TbEV/i09SooCGYKB7XPFSmwHh6E2sX3H2kix8gJO5CJPM7j+1dlt64dgXhZnL8Bp4K2GVSnq7C6Bi7Y46HpOvv9d1zX5qqRrmf0ONyoDFv1uzN7Nk7kKRlQImTxU6YBLsMWrJPgFxMxOaCkwyKspaWx7kTLLYqK4uBPBgWq4gG/ubAvazJUoAlqmV6QhCC3VCVXbGOUJEm
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: slack-webhook-url
      namespace: flux-system

