apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: slack-webhook-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCOsoLi1jS/W9aUniHbUYqeqd7EisCAo6lSvLIXd8yzi5nfFRh2caRbE9sURqgdly9nS9qVEGbX2wyq+8PCKbHZbnUEnPlsfAGF9zZBS39U3DNuoTwC4W0TPnfoQK+vYugtO5NTIUkNzjTHnzWw+eqd/Aq6CGDNr0vWZUSOBITyguJvdGMxVJtr1f4Qeb6VCr4yHSPPN8HARUc+s7kqgEegisGNqFgIrADeaYBPwtfPtSBoecMIJX8PsVamv7Xu7eKzuJQh0DKD67JaGQiMVfmC+pElg8QsUqmoGfyzNtyWqsIo1AYk2dFroQs3t3KHU1uXJVikiSXvu+cCO335swt4E4JDyZah5pfxsbvFPpLamE3nX+s9HSDbGR2Io3bJr5yZB/kYeIj1ubc0G4MrCiUXlJ6uN9EpMIQUVgQEWL1vSQHEsk87okSiEGyeVAIDp2YiXEPQG4kTZjZ+82721CxCIVtgfr+6QPaROweNm8VzL35E5LD43Rohm4e3Hd7w5ZTumQqWGn/0p6aGYFIBkj67uAVsttsCswz0HUSO74aTs9vqwnFkxjtcgg+AQdtvs/JBfqcUBa3sF2pzQss6cdkADlLwgwZZe9TuRwNvodpfwBgLJxfg95v4Zfu34zIkh1RJf0VEgCj/V6uyJdbKm2jsRXkbtDrfVqSc9BtNSeEexBTbRg06r9ptPAJhlLByPrOTvcIzKxMUmp1PQPM2vRl/U9gjLMMZQ9/IrRc2CY9uRTt7waAP+GDpqg7lb03+LbQt3YZrQdSGZOsoL6yk90j/OQht10JwVupCUueaOmrOKSI+
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: slack-webhook-url
      namespace: flux-system

