apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: slack-webhook-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgB5a3xfN1BQ1NnzrlqQ3gffcJtV1ulMNGV/py27Nw5RhUpM4Bv+gVGpOYhecLijcJMJHTJJcmtlVX3WSMBfvYD7me0pviy4wVeoLXUM4tRqqf6vEk/w5JxOZGvBCveK82rgK66Q6adZ4S+tUrUtoAFyL3UNMxBuTBdp+ulfnoAMNzxlH/A9vPGkSyj3LAs6/VG55Y95tsqLRX3YQ7sXDX7GG9DLI49S6Fwmkr4htUDgLvN4LebvMn34IrfruGurYaEjecbjwrNzR/EnltnlaUaiwIeLEU7itE6nGZGvgcMxGYq/buBFw4GWqFygYZBD4zmXCMIElx8o00+SDFJhudInOwdWZuf0Sg5FbC4DbgW0EmBsAusVofadztbVNS+NGK4hG+EbBKDCQzVzFodt+fMer+rPXRzY4NK4Uq36QIHMOaNlLSjtBEcZZtr0Swauqr2Peim/jf6k3fpZWsIpeklWotd5FWNlRAzeNul5RKj2nnCW0xY37RpI/he9KB65Di8XrB8iFaCPFSKjMLcCicrx9nEwQDBONvV4is5jefUdb2okm9RVOTHs5h4uXln/rD0dFtDjI7Q2cDo+R3Ex3iTvyPGgBNDVgTQrDSg2HTKo4gJoxdjIYJmMFHmVHbYftiyPvqiWXfjR51uKlSNa6mcO23vFuqCt5aPGP+TX0oWqTRL1qQZTxeQJ7jvq/6BXCwDMIQLR1EHYyJG6/IacYAqGo6bmT2NTkG/j/40JTHwImRBAcspN23LD/9lXsLCRf9f/5CVVKi/CIz007JNJ5ZL5lX3zv7tylgsgkbyCO53BrPs=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: slack-webhook-url
      namespace: flux-system

