apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: slack-webhook-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAD9bcaoocHnzBPo9Ukoge42abKsVK4BlC+cU1PyGmhAE9PJmKzLORpVrtTyU4b/0hi+sdGFKt5IoTifqvbhyXFlXQQ0IfJ4gO/z67D6H5Rk50pwve1VwCzqeuSI/YqaZm6Yl56xZ9epcw3B+GyPIlWQs58enRSbVS2iJ50djxnBTCZKSYSt0EkjrR7rbO7JsesG3n+733EeG7o3dXrBysHUyqFYMPmZfzfAATnuOUeJvWpoGJAqaD5E5THXL3eFyPySC/+pafKaPAe4cS2RkuS1QmfxYQ9XdU5MwqHfL+CFg6QrHL7kmYf48ukllMg2Zq1/7e7PXM63cLHfoEACWQHlPVQFWlojOHk1tnvBHCj/PN5lQvjX5BdnfiZTQabZCdaPtZi8XstXviOtTaCbb11S3jKTrVbUJLehnlrBTpepUa6s0z+NuW8Tsc4+52PcIE0arRD2l3nzTm2on2U6Rkq7T04bslUTMjSYEZtfGsASZIMgR/CZmsLZpJozDSEbmPKwGjxT/jN9tSrV6Vu8/wjdMlWi1LnRd5gRRpv8XId7TRLCnwNuJiauFYUk0zU+Es/GbeV2WE+FMT/Z6zV3fHCMeNLSiDus1Pkh5oYUFQrhb08ogRvZ5hsjhopbW+X+p5Pq/MeYcjfgVclIx4p04s+IMD+WkQgY3k/qmCOpCj3+fOy9g5iit0K5PKIHne2KswMBLBfBsFtIGZwYpd8PsHFEEMZxO9zIcMZ+rIMVJ1AmXAwWYoSCZu9Zh7MxVouN15CsdDI4cw68+jvPB+c4h1TUYLVziAtiDMi3K9eo68xekgR
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: slack-webhook-url
      namespace: flux-system

