apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
spec:
  releaseName: reloader
  chart:
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  interval: 5m
  timeout: 15m
  values:
    reloader:
      watchGlobally: true
      ignoreSecrets: false
      ignoreConfigMaps: false
      ignoreNamespaces: argo
    deployment:
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-pool-profile
                operator: In
                values:
                - system
    rbac:
      enabled: true
    serviceAccount:
      create: true
    serviceMonitor:
      enabled: true
