---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: st-nowca-wildcard
  namespace: istio-system
spec:
  commonName: '*.staging.nowca.st'
  dnsNames:
    - '*.staging.nowca.st'
    - staging.nowca.st
