---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      # renovate: registryUrl=https://stefanprodan.github.io/podinfo
      chart: podinfo
      version: 5.2.1
