apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: podinfo
  namespace: podinfo
spec:
  hosts:
  - "podinfo.staging.nowca.st"
  gateways:
  - podinfo-gateway
  http:
  - route:
    - destination:
        host: podinfo
        port:
          number: 9898
