---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: podinfo
  namespace: podinfo
spec:
  hosts:
    - 'podinfo.staging.nowca.st'
    - 'podinfo2.staging.nowca.st'
  gateways:
    - 'istio-system/st-nowca-wildcard'
  http:
    - route:
        - destination:
            host: podinfo.podinfo.svc.cluster.local
            port:
              number: 9898
