apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/loki
patchesStrategicMerge:
- |-
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: loki
  spec:
    chart:
      spec:
        # renovate: registryUrl=https://grafana.github.io/helm-charts
        chart: loki-stack
        version: "2.5.0"
