apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/loki
patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: loki
    spec:
      chart:
        spec:
          version: "2.3.1"
