apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: st-nowca-wildcard
  namespace: istio-system
spec:
  servers:
  - port:
      number: 80
      name: http-st-nowca-wildcard
      protocol: HTTP
    hosts:
    - '*.staging.nowca.st'
    - 'staging.nowca.st'
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-st-nowca-wildcard
      protocol: HTTPS
    hosts:
    - '*.staging.nowca.st'
    - 'staging.nowca.st'
    tls:
      credentialName: st-nowca-wildcard-tls
      mode: SIMPLE
