---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: oauth2-proxy-values
  namespace: podinfo
spec:
  encryptedData:
    values.yaml: AgC4Rx2KAYNq9RZaQce5+EtOtmrOtAhBDd7ozswDzy2a4BnGs/9Aqmfd784u16txYzl547NtyF8kGviDFgQggwfMMUE29EWZxrRYWNGN5BiybYnZ8z8bvh1v8HLksSiyrc1gmFi0Yb5vrQXFIzsoRacFOU+M9yCH+1V2X+13Rz3AJEXA9uHMajGt6ALmAomGlzgkdBhspoRKyrk+a267e+Ro3eTXQ9hRtJPIfKUAutpikWl1bPkBuWvMnklxqn9F/KSrSCYsZAsfRwk9KYR+XlCVAxMTEtZMF+o96UBC65CSyatJBwjekvJJtjIJ0UDf6gsj/UeJ0X5lcYajIPxeW/CN020ndUUlfggftT2hK/9fEi0AWVel76yDVB3WaoyPtMLO5BxZq/2EinwHqtCy3bCYQWVtrf+PJ6uYfJ6OMNYBF+J7+XjqtbcnAa8CB9sT5BK7wv0yO2SztmYIT6LXNWsZRR7Kbqvz8AJfi7ggqrIls/P0ZpcshAFA7p2DmKT4Hpt1K/b75j6LxnY+hiiKvAA6ayFk985jd7P+SAOqTHhaiaUhjn6NuQxMCD3sm4aAlC4vGqM0V5X2lA+dlGh1rlCaveEHzN6hSRcw10bC/GYHZ4OgrJdlTMBSgOxkuFI+BhAoANwCZLyaOOhxrvPEXA7e7Muo5QVhpyydBS9HF/tfz8PJUPC33BHhinMz4WJwe186mD0EL4vVq9jGYbxJ1GLwbfcLLADcV7UW4HfO7pA4xFi1MPrwHQOgqHQW6Lrgnh2gknyDl2LgFQuhV2tqW/WUi9hIB3lGzDo/aP+IE/Le/PSc6WptcsyAjAoT1/d3D1Cb4M9duv9NxMx6aMT37kJWtJCXB6l0XwK9nzTtR5aUVpA4hm2evw8brIiy5/ZF1Oxw0KrOUeS9Zv1wPRlnbc8Lwu2eFflQ8V9T3ir0U4PbFoNPZrwH5cXMqCtIxB8NwmYSEEXqPHroJM2I0bdG/xDCUS/6GGX2zkQkVCP6HBRQC6OHnIEp8DucXlaPCz/HecnDTe2oaRY0SyePK4lggFaqayuepI2yG9KqeeCWrya/g9iUZJ4ieD+1X41XeUpocx5t2uSBfAKaj0IMRFv/uGbQ+kSlwETRniU7q3HJQ2yU2s96CJsn17Tha9vytqcY/E2HhzjhXIDtBFv0ETtVJfu+w3Ytxf0FaI3G9OBLkxqMgzUngAa/PiCT+rGb6cMGh/MixvKw2qwZQlMfGja+rKi6iUWFJkLCGDEV/AlcuJDfeLEyvyPjSzjxA8Lrr5JKawtw7eh7E3W0/qSCAdg/uBHE5FvrsdqfqgIsUjhC2L815Xo/CddM1SmkCPnDP2fpkngHdGoSgdQ58/ixrc/rUUzmPY5ZIlAqq0P4SXrw6bJgU2S4BgbaZbZ5VHnq4KhKo17fzW4az2UgcBljxYIlR1H5qwvJatzV75C9Cdt+vPWFcpbvS30l2QPd7IVSQENlbPfxI9wWV+/zV7d4xx0ClfWrqut+cOnIPa18M0CVr6MhQqQxQV7rArh1dSdr4rlMspLnayHr76uF0kA2I/E47YZ84JyWOh4VV7hQzUuh9sGlDNvpG03Dypa6IQHW5p4K+H16ddmLM73o4DtYFNMBcsxiZmKn968uM6MnCu/fM2IvG5y0ji0tyyIv+dtXg+6zQlsjlr7MO666+3nDkORyI7mcNUHDqVXFh6b+ZrIYSMPHTQF2doeyjrazkBkM1ulaTWSETpgg9QCX8Pd9HTEi2VTGLnBtcLU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: oauth2-proxy-values
      namespace: podinfo
    type: Opaque
