---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: oauth2-proxy-values
  namespace: podinfo
spec:
  encryptedData:
    values.yaml: AgC+Cct51u1z7SmVTjNirAuZgSxRxTQJ9KdeGhTfbkutXLPspT3L8YtsLWWId1564nLxeQC/bHI9eeNkvig2s+tFMRX1GvmtZXj1vuqkZ42QOxSBqIddJvLDUyUA66NUUwxWHIvI8RCc5KZfUtDzilSOrMW2gi31KbBVWTpFvd2AEE2btXZcEHKo+9AY82Cf5EfuwLvpDDQO/tv9cd/W2favv3d0lkU2SU4QE40GmHgqpWLsL4B95hgXuNEPZrxKXwQ7nP3SYQa31KTkEPHFGnTH/gHzA+LYvBfUxM6pdj/0AYSce0fCCIkp7VbNZrJ2IAxPfaf7/wTllMdnV4Nf58eMExnzBZlkkWM7RjX3pq1kSt8194qLQMfsHp3labWTiLeyjUeD3TC7vRnysKDesKxE5Lt6DjtBexjNh0dC/vjWnPGuiNUKdmdWfpX9k9rZtVeMYZFjvhGJfL2yUIBYY0UkEwzyhjyTUaGiHxFs7tlARWsAssOQAWArBPsP+IiVz5DQl3aWFsIo3tKiB/f6mu9R7MjOHaKrv/FslQtPbgsu9sSTbC0JeZk20hovQFkIh+VlMSArc10gnz8wgDyKCgzNqBhKSfYFedeFUo5LyJ+yt0J0TD68g+91qaXH4rZrTa9DD35fXLXrE5ey3THtgUzAFuleV8kCUU6UIhFv+d4432CGKUhwQuP/eiSH+lrKAmdVHtpYw1kbQ52RcgkzJsw0eRoLRqVy0srVj+3jlaODYhLlzgsgWWX5Dq/uCEfJ5OdQPEBrGPjDv310ZMH4ptNTRcmugeysacCl8qK/z9ww3mKheca3PfBA2Fu9ej1961Zl+ez6hb9ufmEYdxv/ua+S78IwWDWlz4l1yMM9NPDCaINcfF7R6606jUWDEtkosZQCBbpuatmNB3FpOvEuXJZk5reGqJXV1/vAcTR6ab29qfD++pxvkmooEjATVyQlXcfHAKq6PJbKiC8ihcUapaPQvFqfyrL3HMxwmSHSevQLTPDYRklAR7vtYlgCdDmSMBb8g6PdtsCNzvICwMA5sR5oZyqhgH+GxN98b6ptKFD33JdkpB5Iwy/KXe20BftcvmworSJmDU7tK++SJdbqCNdEZ+KydE4aQUn+/wdddi2plwPDK3ZKQQw089jYd98ungU5dkMo+IWcQvhZlsM+uN4ZCzZOTvJiEjbw8Xezc3nyVB9e9te7N8xo8dw33dlHQwMToTunBHBLEJcq+hUS9GFk9R/XYJup78C5AQ2ztBMb2CTwjzPRHhwtrXrCwtS6xC6YU/CUJAMN0Ecg6iKNy73gnInkcob1+qT2QVm+Soz8hS4zDrkXM4H1hm8dhaK2ZsvEk6JK8HSi0WftyDyz6kP890wbPKsf+tRLtOGynF0CP7KfbuXhHpC9sNe8l2nlKZaqwvWFMnz8hX1ipo38oI6tp+nWz6Q16NgYdJbJy/89HjsNWOMP5v7re7/ngN/opIdbX8hUr5UBbtIO8+W5TYLqYHspptL0PpU2ryvt7nuwQ7gOd63XaOUEpK51jAlgekinCQwJOaoC/s4vMSPPSKPUxyIgLOpMfD5C9OhudJBlRrEc4/XsoB+4kzkLp1lULc0bVRpztDsR7owU6NaKzM/9/00ugyTaTJGyQ3td8m5nu9RQ9hOV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: oauth2-proxy-values
      namespace: podinfo
    type: Opaque
