---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: oauth2-proxy-values
  namespace: podinfo
spec:
  encryptedData:
    values.yaml: AgBV57yX9GdI2M5kcyFsqvizxZ+4f3LbSu9N2VNJxCD8Fzi4i14qhfdLFbrfYH+snvPESkiTA/r7+t8jVAQ7UICaSdTu15shSjftOP/cSss6UwKOA2XksvbkYDNDBhndKgr5im5yKpBNbRfPD/K1+a5gpsWp5cGntrvwUN1Owo9IOHFGJIxbayL2Xw89cW/s+nRG9upJQIcHYdjz7A8LwTHz6RU2bJrskgGJKS3orKdCyZamOLrywa2m0lpO7eVMJjmwNSBfBD4EV9PdE4UvQ/KTJoXhuYk124g9X5xfWppgQCqVXil5itAd7/PuGoQHUCQTPmwylHbEp8J8NeQK47dZ1NORWbkipxlCCheNzXMbsdGlojDI5iCMm5HYLQ9JC4kKgMzs87M6h+F9q3ZknKaDE6DmUqN8jbIlMpQZTtdQU6y98tWp0O8UfOtrSAjrRQyzFRplXyLWKRgJ6TnUJtYMb4CORflbdL5M01DB0c6qr08ii/geD0G11/Jw3LGzBiTRirkHi42BG8x65JEn20PL3hecw/D9eG6GIwyNh9fDbjevytBdZ7zrHVvUBAZzLVVFemSwFWF55aBqy1cR60yNPabdr+w0Q9JcCIKOYfqwNQTEyDCgGU4vkwfm0HLEZy/4AHiHlpuubJeuvMyMKVlZRzrwi8D3u4eyoZzEwfvP/3pOLSbe6gYg5mNpZ5/8lOVh90eKOrkXy2/MeAJ/+c0kV8spvOoabDDpQaSDBGtCjLjjLNFBDFKRHm4HtmTYqL1RPqIWmsrdmObFoXhRDnH7iOZCtoLGRBAFnrud/sMsl486Nv/hq6tZ+2db+VUMWCYNzaP4iKAWc+rUb9/DqoszK92SijRm7fqQwXSgqB2GVAzpaxi2BwYP6aWLwTToSjGlTWxyFTZ/i21VO7cMlbq7lB7cJmMOfiwmxeEmEwaxFl3dRtvXKv0jpCMdnVFmEef0U9zlKxVjY1ykPImYXM4TE+kkD3HIsgh9dVuXeTDUoNrPuyCSJOxLzK/rlsbvWPMlCuBMpn7IwjDWmgSKK0YSekT56m6y3/RX6YWO8GrA6BlgkrtvRivU9kbh5HUn4uX4uToZR4IH/HDud3IszX7hK1lzV9uGd79kL4QMIlUBFLrO1XW2+7Ga65QnUm0bEmBHeQfgx13jJbUiPy+OFuefx7gPpSlN2BHitvVAv0yMdDmAkkqzmhhFFJtxMWXhItIKXjrbGoeOEmdySvLeCgwEQ8AxNTB1AftlQGwg8aurLjDg0vG+oh9GuNUlzJo+zdjT+VB+VgX4TFSp1IDTqHCm42XYe6rSHlgjhHOKnlitKPczO/OVEplRd5llRhXcE4g5wDntdDUUUNKNX7+0XCIU8hABFW0ku8E/2pNO+ozF065U7Wh5OBqmVhykDAF7iEdIlwZN4wFVpVwwqnKhSxQwL9erqXDov3qi5PB3LeiG5uNbHamhyroV+8DBKH0hUdNuQYMXgxEINUl2BZi/02O+nTf0HXScWeYkjVAlqTHwoJtv8SA/QU7Uzya4QtcB0sYWEkaihiEji6zrMqa4V7Q4pcKUa6CWK1MMCvRbxCMAIRz6PZzrry1J6MajoijTXMjW4DTIF62vcFeMust5HlvOv7WwWtyzHyp00gDek9TlLW7q7JZVGbJWPprgH+ulcwZ539Da1uD5R7kzvSGb1GB2vSp7BCOixPFEEvLsZqzazRgTJoYvvJItPZjWwWva4JFKwZx4/OjG/3Kw/dHy5eMpFYlDdAzuOw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: oauth2-proxy-values
      namespace: podinfo
    type: Opaque
