---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: oauth2-proxy-values
  namespace: istio-system
spec:
  encryptedData:
    values.yaml: AgB6N/y7iD6sym2xkQr+BNoTRCkncnPDKvXUgEvfJJcEu5yz3ACULyDJ63XW+tIVvhKAc6b1dIPsYHU69Vx1lL4OE631u9yXE0GUKiJxKQmRrx1XExnyQBwUbSctCI/I5ig0+JxQrjd9zk60aXvCXnuYa6T4xCFkGlF0gkHe5BUt2itiI++4nSC9Yh/vmYkJ/Dkuph+3YKsha5shStyHsJidZksdgdH0sw75fDA1LqSwLlkHdt06gCqFHggHNNBUsDAFW/hHTPy+XBCx83EOTapC10sQjvBdOWixzH8mAdgztT4s/tsEotIATI4KwlfGxFp8Vagh7qDzGn+BrYZ0lsSKCy0JKYyyRvgOzaCSggQYF1m8MVWfdSZaRGJ4qjk3HPeYNv/Vx+A0gIziQpUKFKxf8TeANLnthOxPoAop83ypLfWkljDd0mNDYQRLDiUh13ONRIjCVSLK/emkRYt2eRIw2GJqlg7+TViVV7xqcSgT8xL6t9XtvbWJ8fJhGX8i+oxDJhbAdookmdvaGZDI2UBSYnluVs5gHLaVTN3hnqBM2/hDiNnjstodDONRs04YBxzdDJAAFMOD3znnoS7Uiw94WzKzfqlu7AO7+gGLt/J9lhTIyKsT58xcqoY2UhozEsez93BzTSpAQtEqhwMfHBdx4LpfJtqs3DGM3ykml/jKkK9SAws9tgnZoACscT31O3g/jTR1aTgMQWo0fQzn7IhHCs0Z57617zZc0KlfYyqxBqdkXmxsHY6l6WAgE0z6T05WEHaj/pJcMrLabF9h9sxfHjbtW7525YYYEtbtsyyBomApJUivB3Q5hsgW5D8uEmhTm8HJ2MCCjnDvQmMMlj1XurbIo2CNHXck0vIN+Ahq67i/rjVteV8oPEHTW7u+olnB8BpszbbWB3X6r4H/GbzFuEUjOsvoQO+7YpiQXZ3kkUGlf2/7MCHkscd68M4LYoNzJt0ZzTcwtUXf15TYZ8tT/dg59oCKAVMy4GUZscVsOnuedzb0bXi/b+K2606ObJUTfcXKKLMx833e56KAY6PJfhTzcbPoExGlYZvweT+AJqB0bAwDkKmUOzAnx3U0tdVF55nWKgzy/dzNNAyoPm2c8yVND961a8u1AgNykbLh2O+nbKbTvjpNsg7GdP0Q0f3WbjMoZR8ZU3iAzJt+7n/BFJ7JE7J5kRHVHz2hTs/H0FYQ3a17Bx/MrDXfI1ruR3/5GEqhvjW7Mi8NmzwDJAK9L/Gn/Ib/chkWfBYzJ+DCDWSWqO8W1p1+9Ut12G9yuZHoiNphRQd4K228/lo+yE0gj1Y5XOO437rfk1hjZnYg5uZQtKguiFooFNHrEVMu53hsL45Ynq6EzPAo24epr/PFFA120Lzq8QfdwGBSpoe7F31oakuf7pjG0zSldGAC/xjzmTw3UefMaWXulP0mBETJ5EtNEPsANG9/K9F0EgFodrpqJ2unUqlnzO06IPZeeBRXeEdnVnMfqxUI4AnIXsHZijcc3v5IzHqeDxiBraOgOGY8BuF4k5uS51P1ri+xVqtE6Try09+0jBLiNque93xDQKrr5I7jJ1pH4mOkiX7mFI09dE4m
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: oauth2-proxy-values
      namespace: istio-system
    type: Opaque
