---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: oauth2-proxy-values
  namespace: podinfo
spec:
  encryptedData:
    values.yaml: AgDJLq9gIIEMLQPkf4zNTIXltjSkQp19ijIRhlqSn0Vp7O1Ug25PGTswaMuP0zGA7rdwF8RGZQRHmU8tNU8v8e5XCF4XUyR87CKDLNnni5+jdpTcB+CTTuo535q85Au/ezHBlZsy7ie64k3/SAXK/0no8r9hp46eQNRBMzSu197YRg0QIt7vXmeeKK8AQMaQfOG+Pw9UwBwd5ehKQgu9Nl2myrXS418A5viWqNIQ7pcNFUpA9FdayZLvEH8TFO5LHR3ibJuZ3d3hZpf0A44iQ0GVxNPZ5JNNgEcRMHbuA96f0rd+8bpWBf38CJF+eAns92ULw5EwNQM7YEhqHx7Cm+EzRVrWiZszacRKqyBvhAH9Tp3XqhrFSob3bfgx7EI5kMIme2l4ka0RrO5QD+oOg8P/tRQEjnXPefVpF3AUP7VQI4sgjg+X0I9A2UpXXwQBr+lv4Kp1j8BUXKB3yU6vJhUG5GoIdVsLmuBBRJVkdYy5FjCQsHMLIxUGDJW4tYeVz4BRCdFy4JFy2MOAclTqR0TqxomPv0egjtwuaDbPLQ18N2I2kfAs7Sn4RJb5iDZS/xQqbxAzUF1y0aa3BYKjE7pwwbiD6yQcBZDqZu3NQpDk+sZnKsVpxie7dybQaJRV2TCDmQe7dlW93rUaVt+XuHbrIzug7mrgWEWjeJFDJ3KQhEZBui1hrEX55NQtNH3rz3P0osFP4Hi4/0EfeMbuJwUlUqwnNzog2R6lIatwQSMP87tRygkZB6OppDY+y8IZLHle2exr/C7Xsl2wtkCSBxPcLUAHXZ7mDrk3BbZBSn6n73SWSdYOiCvCUMmRl0b94XAX9Fxb1wMg15/JSjuhzzWkifvXc4aIkU0P6P3dnwdCSSFFHYrGUBjr72ZsiDoFgWM3pLrLi8WqkTV+oF7QNcpkE2xxm3i4QgUX9irjgxk7VdP46xaF3YeickcO0RMpcjgNSIOM8by/GwrfI+R/v5VxyLwCepxBtg3yIQPWoRfHwreqLktowOTG7V6FbogEPl5xFQl+pqktZCng+FDG7KFERMfrDwY7pC6moR2577R9ZeSbbkXAJ8Je1b8mK2h0BpRHeO+W5MnbCBPtmTlhYjJkON55t9X1Q6JNFrRHzWQrJuXG2U642CtQ3griFezqXyLw5VymSIZbZF8wXhIEUyDblQciI/fEyusEerzUkqv/m3ANYBOnDyLkQH6lHc5V/KN/lQ/bBjf2tc3y4/uCTZ7BDj/BoWBk+ERlbsHXHmaNid1P45hKz9wrsJe9CKn+eyTvfqNh6KCrYAfRzuU02PfK+4ktqxkw7h9BVx8uVk1ZuPHre4MiR7Z/dTuG79WhmNeXHf+QMgKLd19ionek6wmsW7A2JUNDlKghbDhsvPytXr/p1n7fnB0eVuNc+xw2FZiAnay915W8+r0J3uwH6HMrmFuPSvbIptRNK5SueFICe+jwN8JGc0bL5Cffml1e3FgE0DnHbdjO1j7RL/ryIkRDO5sX7zCttC1KrXv/K3/MWig8AjdsK0l4Q1De5kObKkmJjIYUnaBmmDCjzrKd9444gsS73uOnpH5AIp3fQBxbN3i22P2aBz2EU9BEvVbVLcVAvn2CejYJCF42uhOEhD1RmXUEjumRpozm8F7PJFa9EqHqHuF84xmvl9yHpiZS2+fDdl/4yYhB0uJMjTIE/d/SY6QgH4Upo4DQCWwJXQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: oauth2-proxy-values
      namespace: podinfo
    type: Opaque
