---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: oauth2-proxy-values
  namespace: podinfo
spec:
  encryptedData:
    values.yaml: AgDErl6qX0RUiyvw9kYTvIe4fbmczGjesqVYTpghjk+ZGIwNhMo+4SCFQS84DpmioYDSBSi8xl6x8sbIp5iqiK1/HPmyqX9QBihi20pTjq3PoTTc0OQsv/Ay07Ch5Oy0WWNVTj8e28h/+94I3zwAFvM+NhhzKAsrsTyRmpoIFMzKhAnJjV1ENIDJOLCnYs7FaOGA8p67EaZDX0X2hxacAQtk+8vIDvgiV750kTeKuqF7JigflKq3A/+ZijS/9MlJtzuyWXRfCtjrayQNzHbOHjd2Eu1PF6ltrLhbP5MUG7lY50VE9eonbimNL1FGwG+fXlFmj4ayGunumH487gQpsykeLhDkjGkaPni7lyhY6Ok2bIi3EkW2LHkntEJA+8PTtrUy+ICZjaslKgLh7D2KQfnmUm+tlNHcciEjlO4CL/q6Fv+GU9OVkaIoi6sZW4atdtqm63IASU85e3WhjqnZDc8JSyE5SS61NLPApYX8lCOkaR2B1tFcMWXpqfN0pGhlsaf6i5UZ9f5NYwJSpK4sSwBFiyWSQUww9gijmpQwY/LowzsR6z2OY/A90P3/BwI+4m4WdVW/8kSG76zwxI2Ndt4EVGf9UCOL5kqMZH9AYeZ9wcRgX5QFrK/UCTHW/3os0ZVOgtaM2Xzcbpd7Ua/lQTG7vJFB4gWXYvy5AjC+pdGEFbYPRXITja9gLKizvz2wL7+Y7CWsIvtzpMKGhZFEtx70t/gvoGQ8TtagRmSBco8sf5J8O2UN6sX/1RmilFBB1f7qHRhgvbdxofEeqCkPF63/h73CEdT8Q3gX5PvCng0mAZK/2X4EpIhbeRlqDDvbEGh+APkzCNPTEeVqJN7coZKHWz9a15vgDF2zF0czQq/vRbxl9HdU6Rx3+g3pqZIROcavwN7sunXHLufAa8UcJtprhq6of6U4eu+sxyEbI81K1TiKXXCxccQy4aKmt5zr6TOvSVrUnwN3suPUbL1/+4POHvPrHs3kKw0yENhXiVpgrvuPCgzDP0ryiQ4kmPsM0phxoRsqC3CfCoqDqI4qWi4HLhTzW0KGzkbl7c44iHS95Oq1+jxQcvVbAdVBecdZqL07eKBYpHOCNQzRVQfJExVrh/pPC4ceSm6y1vVqTZQQrle/ciXag3/PYBOsDxAWcQb7M/X8R7G6gTGEJWAHVa+sXUbONqaWTgjuQckxH+s4FKd5M/SfPbVlOSCTvFfUB5DFy5+REdOKFLaxaWeGUvm2lBJurnKYltquOKnkASId+PzI64Dq1d76NFH5TrKwaCA/xpaj1TciJHzAM/Ep9N8AjHAmUgmP07Ox5jpIc9osRVGS+jGwrE3ZLtijso6ttZBsw4nkDAdXx+9UjgeWOxRuEP9Vs0AnL0b0ZIEPWfEV1cUQ0cTdxU8fgZ4fL1gdKPS0xfom2tXt+1Yv+So1y8zH43WcH1QvEPwzKaT28fM6+S4dObtyb/gCdhHdAi4NsIrGTeY8vy3jxRLWfBMhTrhZRZkOcWoRFhzNI3tKG7cQp7kHXG0JnvjwOC7hD1Vna7EvchxQVVkX1gms/KvKJGqLfasuNg6ti6PtQ8kxyi87AA0lR3+b4+PG8tBzpHQlrb0yUvb5PUwQwab1HMDZwwL5aK3kdrtrg683x1quQaMUu27giNyMevjDci8z+Tm4yrgavpwaLzKmGMXwYrsNV0oOdWyEsXVMIkc8EtLpQP8mXxTxgcBTL1W2jBZBEXTEEjnJLA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: oauth2-proxy-values
      namespace: podinfo
    type: Opaque
