---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: oauth2-proxy-values
  namespace: podinfo
spec:
  encryptedData:
    values.yaml: AgCDFV8uRy4Mokuun10dI2a7Jq/ITJ7ixgKGfpUrSX12inp1X+GapGSSDglyBZR9aXfoQCEPlc5Mov/tixY4WUCROoQ7B/SH9khMBv06d5akUSC8p3IuKjx0slkriBD/YNrul5n9thbdrDJfPrGR1BdW8X2LIUvzjYp0I2BpDpnM16jXIjaQldS9B1VFiDyQzTTNkMsnMCbiL1IKB44tbPIOGGt4pXIvqm/Ws1ZgMWY2Z56n0nw3lJBcx7k5AiS9BTdzCScwNd+e/E9fS7pcd7lids0pfQgvSTY9ft6ctGT8Lxi5KrSuATeDbTEkOT4eKHPvaoDj31AncwjI+ZPKkLJnW4eC5DTfvgJdWkhg39D1y7RUbu4dIo/ukdeWpxX2JgYZ5rBK22QoNebzGhqzu8CdDHp7AOxzkAYV6g5vojFTDy+6MdR5orWOl0v/F2g7Lq5fPIhg1Zfmodmun1elfLi4H23nQU12eOebG4AIRPUZYSUdtMVEIilO78guC6XxVXbhPQ/0MGzwTF3z6xIGN119RAl7BBDISF8qQqbBurzXMOLgPcQtZf8p2Rgc6ATwys0acWExARi0uEmbRWjIRfsCl78TiOM+L04/JlJDObQoE54MFJuZ58YXeyju21aVSGh5D3T9BTwpsW1O7+5TYytwlaEjDyF0ZTWrr0agckusjrfZG2WN9JnhQC5FsWuzsQe5kyqtR0PVFuha09mAjjAdE4aS+zOQwZTAOcJO4Pk0Pe/VwTAv1S9Kz4Rjv67hx0DAsYpLt8dbZRBXJa8erz2C+iSLSwy28F+jy0/bBg+VC5Dy7Khc4yrbucvcSPsPCnl6CQ9SBQSrSbqX2cAfocQ7c/n+oTVlRPGoy/HSzWpAsqqRtyDlvfYIa0iGissB5FIKYfAdl2BROZvZCdXEh8332XmzXBlJkmw5VhwVP2RheZ3i40zsWOKPLAYTtqzLu1+Jg7+GovLaJyom8Ej3L0KqLLXCvzcQy60UjwuUnw/9cjSFuHAoIcvDuwFKXY7b7XHzoVsfgacFaaFE0270Pwa8+QOkQ5pnguUNEp8miKwB9K15kHwg7u8gYM2ffrBecf3kl7qhCVt8m1B1p1B1QJwLvHUpebOKjBun3RCV3mihJb4imAPISzhj7qS3ciVKIW5KNq3Xzj+KHzw7AGtlBStnTFmMJ6dd6GqSn7CUOolNQyqCTiqXVC4SonYRCz6LZ+IAtoAxHmNs3ysatFUQlbNg+tV3DRfs631vbuqTJgbUXaibDzAwAwVkOXuIVhm8EkjWpMzlOFfsYhyUe9AXMlw15AARsEQUkXPbdwdMtIdDXcbSrEtbC1E118/ROC2crEqCIbOt0MakEALqo6+t17IeX4FtKkGiNz8sdVr+20aDUk5iGxMEyrefciZp3ja45Z6RathKKx+eM5SMScIltVXCiBHz3CCfB+ymSXmaYhXYE/ZnSVZXSqRMBk0P/lRC5hOQLzypl3DkkvfolW8b4z4BQpZ5ExkgcmNq/6T7OwjcqXP9tG0ZqLMjE0hZIP3R1G0D5jE0C2xCcWardWpPkNqA4lFr2eZj+Xn5pUFDUCBqCHNPe58eXIweiXEOQRZ3NLqGh+xVUCJRJDzFQ/0A2S/TJv1CfuK9kkXPsslVCrBJGBSE5z0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: oauth2-proxy-values
      namespace: podinfo
    type: Opaque
